#Commit to trigger build
version: 2.1

setup: true

orbs:
  docker: circleci/docker@2.0.1

jobs:
  build:
    docker:
      - image: 'circleci/buildpack-deps:stretch'
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: brianoh1979/circleci-demo-docker4
      - docker/push:
          image: brianoh1979/circleci-demo-docker4:latest
      - run:
          name: Install cURL and jq
          command: sudo apt-get update && sudo apt-get install jq curl
      - run:
          name: Generate /tmp/another-config.yml
          command: |
            cat \<< EOD | tee /tmp/another-config.yml
            version: 2

            jobs:
              build:
                docker:
                  - image: brianoh1979/circleci-demo-docker4:latest
                steps:
                  - run: echo "Hello from another workflow!"
            EOD
      - run:
          name: Build a valid JSON message using jq and write it to /tmp/continue-body.json
          command: |
            jq -n\
              --arg continuation "$CIRCLE_CONTINUATION_KEY" \
              --arg config "$(cat /tmp/another-config.yml)" \
              '{"continuation-key": $continuation, "configuration": $config}' | tee /tmp/continue-body.json
      - run:
          name: Execute another config
          command: |
            curl \
              -f \
              -X POST \
              -H "Content-Type: application/json" \
              --data-binary @/tmp/continue-body.json \
              https://circleci.com/api/v2/pipeline/continue
